[package]
name = "storage"
version = "0.3.1"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = { workspace = true }
redb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tantivy = { workspace = true }
tracing = { workspace = true }
chrono = { version = "0.4.44", features = ["serde"] }
walkdir = "2.5"
dashmap = "6.1.0"
xxhash-rust = { workspace = true }
sysinfo = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
tempfile = "3.27.0"
