[package]
name = "storage"
version = "0.2.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
redb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tantivy = { workspace = true }
tracing = { workspace = true }
chrono = { version = "0.4.42", features = ["serde"] }

[dev-dependencies]
uuid = { workspace = true }
tempfile = "3.8"
